language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test

    packages:
      - clang-3.6
      - cmake
      - cmake-data
      - doxygen
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9

    - compiler: gcc
      env: COMPILER=g++-5

    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.6

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script:
  - make
  - make doc
  - make test
