language: c++
os: linux
dist: trusty
sudo: false

addons:
  apt:
    sources: &apt_sources
      # Distributions for LLVM may be found here: http://apt.llvm.org/trusty/dists/
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test

    packages:
      # Packages needed for all of the builds.
      - cmake
      - cmake-data

matrix:
  include:
    # Default on Trusty is gcc-4.8.4
    - compiler: g++
      env: COMPILER=g++

    # Install and test with gcc-5.4.1
    - compiler: g++-5
      env: COMPILER=g++-5
      addons:
        apt:
          sources: *apt_sources
          packages:
            - g++-5

    # Install and test with gcc-6.3.0
    - compiler: g++-6
      env: COMPILER=g++-6
      addons:
        apt:
          sources: *apt_sources
          packages:
            - g++-6

    # Install and test with gcc-7.2.0
    - compiler: g++-7
      env: COMPILER=g++-7
      addons:
        apt:
          sources: *apt_sources
          packages:
            - g++-7

    # Install and test with Clang 4.0.1
    - compiler: clang++-4.0
      env: COMPILER=clang++-4.0
      addons:
        apt:
          sources: *apt_sources
          packages:
            - clang-4.0

    # Default on Trusty is Clang 5.0.0
    - compiler: clang++
      env: COMPILER=clang++

    # Install and test with Clang 6.0.1
    - compiler: clang++-6.0
      env: COMPILER=clang++-6.0
      addons:
        apt:
          sources: *apt_sources
          packages:
            - clang-6.0

    # Install and test with Clang 7
    - compiler: clang++-7
      env: COMPILER=clang++-7
      addons:
        apt:
          sources: *apt_sources
          packages:
            - clang-7

before_script:
  - mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script:
  - make && make test
