language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - cmake
      - cmake-data
      - doxygen

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make doc
  - make test
