language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test

    packages:
      - clang
      - cmake
      - cmake-data
      - doxygen
      - gcc-6
      - g++-6

compiler:
  - clang
  - gcc-6

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make doc
  - make test
